package module.commands;

public enum CommandType {
    NON_ARGUMENT_COMMAND,
    LINE_ARGUMENT_COMMAND,
    OBJECT_ARGUMENT_COMMAND,
    LINE_AND_OBJECT_ARGUMENT_COMMAND,
    SCRIPT_ARGUMENT_COMMAND
}
